server:
  port: 9000

spring:
  application:
    name: zuul

zuul:
  routes:
    cartao:
      path: /cartao/**
      serviceId: cartao
    cliente:
      path: /cliente/**
      serviceId: cliente
    pagamento:
      path: /pagamento/**
      serviceId: pagamento
    cep:
      path: /cep/**
      url: http://viacep.com.br/ws

ribbon:
  ConnectTimeOut: 10000
  ReadTimeout: 10000

